sqlite3_config: &sqlite3_config
  adapter: sqlite3
  database: db/test.sqlite3

postgresql_config: &postgresql_config
  adapter: postgresql
  database: gem_test
  username: postgres
  password: password
  host: localhost

mysql_config: &mysql_config
  adapter: mysql2
  database: gem_test
  username: mysql
  password: password
  host: 127.0.0.1

test:
  <<: *<%= "#{ ENV['DB_ADAPTER'].presence || 'sqlite3' }_config" %>

development:
  <<: *sqlite3_config
