name: spec

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  #
  # Runs on EVERY push to ANY branch (but skip if it's a PR)
  main_suite:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Main RSpec Tests (run using main Gemfile and SQLite)
        run: bundle exec rake spec

  #
  # Runs ONLY on Pull Requests
  compatibility_matrix:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 3.4 ]
        appraisal:
          - rails-6-1
          - rails-7-2
          - rails-8-1
        database:
          - mysql
          - postgresql
          - sqlite3

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: gem_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:lts
        env:
          MYSQL_DATABASE: gem_test
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
          MYSQL_RANDOM_ROOT_PASSWORD: true
        ports: ['3306:3306']
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies for Appraisal
      run: bundle exec appraisal install
    - name: Run RSpec compatibility tests for [${{ matrix.appraisal }}] using [${{ matrix.database }}] database
      env:
        DB_ADAPTER: ${{ matrix.database }}
      run: bundle exec appraisal ${{ matrix.appraisal }} rake spec
